<!DOCTYPE html>
<html lang="fr-FR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form</title>
</head>
<body>
    <?php if ($_GET['register'] === 'false'): ?>
        <h1>Inscrivez-vous !</h1>
        <form action="" method="post">
            <input type="text" name="firstname" id="firstname">
            <input type="text" name="lastname" id="lastname">
            <input type="text" name="login" id="login">
            <input type="password" name="password" id="password">
            <input type="email" name="email" id="email">
            <input type="submit" value="">
        </form>
    <?php else: ?>
        <h1>Connectez-vous !</h1>
        <form action="" method="post">
            <input type="text" name="login" id="login">
            <input type="password" name="password" id="password">
            <input type="submit" value="">
        </form>
    <?php endif; ?>
</body>
</html>